# Generated by Django 6.0.5 on 2026-05-17 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibonacci', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Foto Extra')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fibonacci.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Foto Extra do Produto',
                'verbose_name_plural': 'Galeria de Fotos do Produto',
            },
        ),
    ]
